/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covidvaccination;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius Russo
 * @title DATA STRUCTURES AND ALGORITHMS – Assignment (50%)
 * @date March 2021
 */

public class GUI extends javax.swing.JFrame {

    private PQInterface myPQ;
    int priorkey;
    int age;
    Integer ageINT;
    String name;
    boolean condition = false;
    PQ all;
    int newKey;
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        myPQ = new PQ();
        all = new PQ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup = new javax.swing.ButtonGroup();
        titleLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        ageTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        exitBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        radioYes = new javax.swing.JRadioButton();
        radioNo = new javax.swing.JRadioButton();
        totalBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        nextGroupBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        scheduleBtn = new javax.swing.JButton();
        totalScheduled = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to the Vaccination App");
        setBackground(new java.awt.Color(102, 174, 174));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        titleLbl.setFont(new java.awt.Font("Baloo 2", 1, 36)); // NOI18N
        titleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-virus.png"))); // NOI18N
        titleLbl.setText("Covid-19 Vaccine for Ireland ");

        nameLbl.setFont(new java.awt.Font("Baloo 2", 0, 24)); // NOI18N
        nameLbl.setText("Name: ");

        nameTxtField.setFont(new java.awt.Font("Baloo 2", 0, 18)); // NOI18N
        nameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtFieldActionPerformed(evt);
            }
        });

        ageTxtField.setFont(new java.awt.Font("Baloo 2", 0, 18)); // NOI18N
        ageTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTxtFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Baloo 2", 0, 24)); // NOI18N
        jLabel1.setText("Age:");

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        exitBtn.setBackground(new java.awt.Color(255, 153, 153));
        exitBtn.setFont(new java.awt.Font("Baloo 2", 0, 14)); // NOI18N
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-exit_sign.png"))); // NOI18N
        exitBtn.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-exit_sign.png"))); // NOI18N
        exitBtn.setFocusTraversalPolicyProvider(true);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Baloo 2", 0, 24)); // NOI18N
        jLabel2.setText("Condition:");

        buttonGroup.add(radioYes);
        radioYes.setText("Yes");
        radioYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioYesActionPerformed(evt);
            }
        });

        buttonGroup.add(radioNo);
        radioNo.setText("No");
        radioNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNoActionPerformed(evt);
            }
        });

        totalBtn.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        totalBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-people.png"))); // NOI18N
        totalBtn.setText("Total Registered");
        totalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBtnActionPerformed(evt);
            }
        });

        addBtn.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-add.png"))); // NOI18N
        addBtn.setText("Add Patient");
        addBtn.setFocusTraversalPolicyProvider(true);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        nextGroupBtn.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        nextGroupBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-forward_button.png"))); // NOI18N
        nextGroupBtn.setText("Next group to be vaccinated");
        nextGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextGroupBtnActionPerformed(evt);
            }
        });

        displayBtn.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        displayBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-select_all.png"))); // NOI18N
        displayBtn.setText("Display All Registered");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        scheduleBtn.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        scheduleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-schedule.png"))); // NOI18N
        scheduleBtn.setText("Schedule");
        scheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleBtnActionPerformed(evt);
            }
        });

        totalScheduled.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        totalScheduled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-total_sales.png"))); // NOI18N
        totalScheduled.setText("Total Scheduled");
        totalScheduled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalScheduledActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(totalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalScheduled, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(radioYes))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(ageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(radioNo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextGroupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scheduleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleLbl)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(356, 356, 356))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameTxtField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(radioYes)
                            .addComponent(radioNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(displayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scheduleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextGroupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(totalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(totalScheduled, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtFieldActionPerformed

    private void ageTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTxtFieldActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // To exit the application
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void radioYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioYesActionPerformed

    private void radioNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNoActionPerformed

    private void totalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBtnActionPerformed
    // Check size of list which will be how mony people are resgistered
        int total = all.sizeTotal();

        textArea.setText(""); 
        textArea.append("Total people registered: "+ total +"\n");
        
    }//GEN-LAST:event_totalBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
    // Adding patients's names, age and if condition is has any medical condition or not (true or false)
        
        // This if statement was made to inform user that is necessary to fill all information for registration
        if(nameTxtField.getText().isEmpty() || ageTxtField.getText().isEmpty() || (radioYes.isSelected()==false && radioNo.isSelected()==false)){   
            JOptionPane.showMessageDialog(this, "You must fill all information");
        } else {
            Patient pt = new Patient();

            // Taking name from Text Field and assigning to variables
            name = nameTxtField.getText();
            ageINT = new Integer (ageTxtField.getText());
            age = ageINT;

            if(radioYes.isSelected()){
                condition = true;
            }else{
                condition = false;
            }
            
            pt.setName(name);
            pt.setAge(age);
            pt.setCondition(condition);

            // Adding to queue
            all.enqueue(pt);

            // Display item added
            textArea.setText("");
            textArea.append("Patient " + pt.getName() + " was added successfully");


            // Add to priority queue withouth index yet
            myPQ.enqueue(pt);


            // Clear all input areas
            nameTxtField.setText("");
            ageTxtField.setText("");
            radioYes.setSelected(false);
            radioNo.setSelected(false);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void nextGroupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextGroupBtnActionPerformed
    //  It will show next group to be vaccinated according to their priority
    
        if(!myPQ.isEmpty()){
            
            // This should get the first element key on the priority queue
            PQElement headElement;
            headElement = myPQ.getElement(0);
            int firstKey = headElement.getKey();

            do{
                Patient temp = (Patient)headElement.getElement();
                name = temp.getName();
                age = temp.getAge();
                condition = temp.condition;

                myPQ.dequeue();


                if(myPQ.isEmpty() == false){
                    PQElement nextElement = myPQ.getElement(0);
                    newKey = nextElement.getKey();
                }

            }while(newKey == firstKey && myPQ.isEmpty() == false);


            // This part check which group is the next one to be called to be vaccinated

            // String to hold output message
            String nextGroup = "";

            if(firstKey == 10){
                nextGroup = "Next priority group is 10 - People aged 90 and older";
            }else if(firstKey == 9) {
                nextGroup = "Next priority group is 9 - People aged 80 and older";
            }else if(firstKey == 8){
                nextGroup = "Next priority group is 8 - People aged 70 and older";
            }else if(firstKey == 7){
                nextGroup = "Next priority group is 7 - People aged 65 and older";
            }else if(firstKey == 6){
                nextGroup = "Next priority group is 6 - People aged 18-64 with medical condition(s)";
            }else if(firstKey == 5){
                nextGroup = "Next priority group is 5 - People aged 55-64";
            }else if(firstKey == 4){
                nextGroup = "Next priority group is 4 - People aged 45-54";
            }else if(firstKey == 3){
                nextGroup = "Next priority group is 3 - People aged 30-44";
            }else if(firstKey == 2){
                nextGroup = "Next priority group is 2 - People aged 18-29";
            }else if(firstKey == 1){
                nextGroup = "Next priority group is 1 - People aged under 18";
            }else{
                nextGroup = "No more patients to be vaccinated";
            }

            textArea.setText(""); // To clear text area before new output
            textArea.append(nextGroup); // Displays next group to be called
        
        } else{
            textArea.setText(""); // To clear text area before new output
            textArea.append("No one to be vaccinated");
        }    
            
        
    }//GEN-LAST:event_nextGroupBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        textArea.setText("");
        textArea.append(all.toString());
        
    }//GEN-LAST:event_displayBtnActionPerformed

    private void scheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleBtnActionPerformed
        // Checking which priority should be given to patients added
        
        if(!myPQ.isEmpty()){
            textArea.setText("");
            textArea.append(myPQ.printPQueue() + "\n");
        } else{
        textArea.setText("");
        textArea.append("No one to be scheduled");   
        }    
    
    }//GEN-LAST:event_scheduleBtnActionPerformed

    private void totalScheduledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalScheduledActionPerformed
        // TODO add your handling code here:
        textArea.setText("");
        
        int totalScheduled = myPQ.size();
        textArea.append("Total of people already scheduled: "+ totalScheduled +"\n");
    }//GEN-LAST:event_totalScheduledActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField ageTxtField;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton displayBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JButton nextGroupBtn;
    private javax.swing.JRadioButton radioNo;
    private javax.swing.JRadioButton radioYes;
    private javax.swing.JButton scheduleBtn;
    private javax.swing.JTextArea textArea;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton totalBtn;
    private javax.swing.JButton totalScheduled;
    // End of variables declaration//GEN-END:variables
}
